import {RFValue} from 'react-native-responsive-fontsize';

const Theme = {
  colors: {
    appColor: '#363636',
    // appColor: '#0079FF',
    white: '#FFFFFF',
    black: '#000000',
    transparent: 'transparent',
    transparent80: '#00000099',

    bgColor1: '#363636',
    bgColor2: '#F7F9FC',
    bgColor3: '#0079FF',

    borderColor1: '#1525A3',
    borderColor2: '#F7F9FC',

    textColor1: '#F7F9FC',
    textColor2: '#363636',
    textColor11: '#F30000',
  },
  fontFamily: {
    // Lato
    fontLatoBlack: "Lato-Black",
    fontLatoBlackItalic: "Lato-BlackItalic",
    fontLatoBold: "Lato-Bold",
    fontLatoBoldItalic: "Lato-BoldItalic",
    fontLatoItalic: "Lato-Italic",
    fontLatoLight: "Lato-Light",
    fontLatoLightItalic: "Lato-LightItalic",
    fontLatoRegular: "Lato-Regular",
    fontLatoThin: "Lato-Thin",
    fontLatoThinItalic: "Lato-ThinItalic",
  },
  responsiveSize: {
    size1: RFValue(1),
    size2: RFValue(2),
    size3: RFValue(3),
    size4: RFValue(4),
    size5: RFValue(5),
    size7: RFValue(7),
    size8: RFValue(8),
    size10: RFValue(10),
    size11: RFValue(11),
    size12: RFValue(12),
    size13: RFValue(13),
    size14: RFValue(14),
    size15: RFValue(15),
    size16: RFValue(16),
    size18: RFValue(18),
    size20: RFValue(20),
    size22: RFValue(22),
    size25: RFValue(25),
    size28: RFValue(28),
    size30: RFValue(30),
    size32: RFValue(32),
    size36: RFValue(36),
    size38: RFValue(38),
    size45: RFValue(45),
    size50: RFValue(50),
    size70: RFValue(70),
    size80: RFValue(80),
    size100: RFValue(100),
    size130: RFValue(130),
    size170: RFValue(170),
  },
  icons: {
    icEyePasswd: require('../resources/ic_eye_passwd.png'),
    icEyeOffPasswd: require('../resources/ic_eye_off_passwd.png'),
    icIcon: require('../resources/ic_icon.png'),
    icMenu: require('../resources/ic_menu.png'),
    icAdd: require('../resources/ic_add.png'),
    icKey: require('../resources/ic_key.png'),
    icKeyLeft: require('../resources/ic_key_left.png'),
    icClose: require('../resources/ic_close.png'),
    icLogout: require('../resources/ic_logout.png'),
  },
};

export default Theme;
